### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by sergesby** [marcelog/PAMI#171]
Hello dears!
i don't understand what going on, but i can't connect to * ami:

here is error log:
`Stack trace:
#0 /var/www/localhost/htdocs/callme/vendor/marcelog/pami/src/PAMI/Client/Impl/ClientImpl.php(265): PAMI\Client\Impl\ClientImpl->getMessages()
#1 /var/www/localhost/htdocs/callme/CallMeIn.php(237): PAMI\Client\Impl\ClientImpl->process()
#2 {main}
  thrown in /var/www/localhost/htdocs/callme/vendor/marcelog/pami/src/PAMI/Client/Impl/ClientImpl.php on line 242
PHP Fatal error:  Uncaught PAMI\Client\Exception\ClientException: Error connecting to ami: tcp://127.0.0.1:5038 111 Connection refused in /var/www/localhost/htdocs/callme/vendor/marcelog/pami/src/PAMI/Client/Impl/ClientImpl.php:178
Stack trace:
#0 /var/www/localhost/htdocs/callme/CallMeIn.php(42): PAMI\Client\Impl\ClientImpl->open()
#1 {main}
  thrown in /var/www/localhost/htdocs/callme/vendor/marcelog/pami/src/PAMI/Client/Impl/ClientImpl.php on line 178`

it seems what port 5038 is blocked or closed, but no.
in the asterisk console i have:

`gentoo*CLI> manager show connected
  Username         IP Address                                               Start       Elapsed     FileDes   HttpCnt   Read   Write
  callme           127.0.0.1                                                1534880661  658         21        0         04079  04863
1 users connected.
gentoo*CLI>`

please, help me...

**Comment by sergesby** [comment]
sorry, with PAMI and asterisk all ok....
closing.
